language: python

python:
  - 3.5

env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=pypy
  - TOX_ENV=pypy3

install:
  - pip install "virtualenv<14.0.0" "tox>=2.3.1"

script:
  - tox -e $TOX_ENV
